services:
  api_course:
    build: .
    restart: always
    ports:
      - "5555:5555"
    environment:
      - PORT=5555
      - MONGO_URI=mongodb+srv://maks:ustazschoolbot@cluster0.ne5oyfn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster
    networks:
      - proxy-net
  
networks:
  proxy-net:
    external: true
